apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: check-branch
spec:
  entrypoint: check-branch
  templates:
  - name: check-branch
    inputs:
      parameters: 
      - name: expectedBranch
      - name: actualBranch
      - name: buildImage
    script:
      image: "{{inputs.parameters.buildImage}}"
      workingDir: /src
      command: [bash]
      source: |
        actualBranch="{{inputs.parameters.actualBranch}}"
        actualBranch=${actualBranch#refs/heads/}
        expectedBranch="{{inputs.parameters.expectedBranch}}"
        echo "branch that triggered job was ${actualBranch}, expected branch was ${expectedBranch}"
        if [ $actualBranch == $expectedBranch ]; then
          echo "expected branch matches actual"
        else
          echo "this is not the expected branch. terminating pipeline."
          exit 1
        fi
      envFrom:
      - secretRef:
          name: ci-secrets
      - configMapRef:
          name: ci-cm

