apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-publish-image-to-gcr-virtru-public
spec:
  entrypoint: publish-image-to-gcr
  templates:
  - name: publish-image-to-gcr
    inputs:
      artifacts:
      - name: repo-source
        path: /src
      parameters: 
      - name: buildImage
      - name: projectName
      - name: dockerTag
    container:
      image: "{{inputs.parameters.buildImage}}"
      command: [sh, -c]
      workingDir: "/src/{{inputs.parameters.projectName}}"
      args: ['
          /setup-build-env && 
          ls -la && 
		  pwd &&
          docker ps &&

          export TAG=2.14.0 &&
          export DEPLOYER_VERSION=${TAG%.*}
          export REGISTRY=gcr.io/virtru-public/staging/gateway &&

          echo "TAG=$TAG" &&
          echo "DEPLOYER_VERSION=$DEPLOYER_VERSION" &&

          echo "INFO: Pull gateway image from dockerhub" &&
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD &&
          docker pull virtru/gateway:$TAG &&
          docker logout &&

          echo "INFO: Configure credentials for GCR" &&
          echo "$GCR_VIRTRU_PUBLIC_JSON_KEY" > /tmp/gcr_virtru_public_json_key.json &&
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcr_virtru_public_json_key.json &&
          go get -u github.com/GoogleCloudPlatform/docker-credential-gcr &&
          which docker-credential-gcr &&
          docker-credential-gcr config --token-source="env" &&
          docker-credential-gcr configure-docker &&

          echo "INFO: Push gateway image to GCR" &&
          docker tag virtru/gateway:$TAG $REGISTRY:$TAG &&
          docker push $REGISTRY:$TAG &&
          docker tag virtru/gateway:$TAG $REGISTRY:$DEPLOYER_VERSION &&
          docker push $REGISTRY:$DEPLOYER_VERSION &&

          echo "INFO: Build and push deployer image" &&
          docker build --no-cache --build-arg TAG="$TAG" --build-arg REGISTRY="$REGISTRY" -t "$REGISTRY/deployer:$DEPLOYER_VERSION" -f dev.Dockerfile . &&
          docker push $REGISTRY/deployer:$DEPLOYER_VERSION
          ']
      env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: AWS_PROFILE
        value: mgmt
      envFrom:
      - secretRef:
          name: ci-secrets
      - configMapRef:
          name: ci-cm
    sidecars:
    - name: dind
      image: docker:19.03.13-dind
      env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      securityContext:
        privileged: true
      mirrorVolumeMounts: true

