apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  # Use a single replica. Multiple replicas may cause duplicate billing.
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ubbagent
          image: {{ .Values.ubbagentImage }}
          env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: consumer-id
            - name: ENTITLEMENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: entitlement-id
          volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
        - name: billing-helper-{{ .Chart.Name }}
          image: alpine:latest
          # This container runs a curl command on infinite loop. The curl posts usage data to ubbagent.
          # see https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/billing-integration.md#sending-usage-reports
          # Inputs:
          #  .Values.pricingPlan is from a pulldown/enum on the config page. It corresponds to the metric names.
          #     Example: gateway___gmail_encryption__per_user_
          #  .Values.numberOfLicenses is also from the config page.
          #     The customer enters the number of licenses for their subscription.
          command:
          - "/bin/sh"
          - "-c"
          - |
            apk add curl
            echo "Starting billing helper. pricing plan: {{ .Values.pricingPlan }} ; licenses {{ .Values.numberOfLicenses }}" >&2
            # Give ubbagent time to initialize
            sleep 10
            while true
            do
              # report a time range from the start of the current hour, to the end of the current hour
              timestamp="$(date -u +"%s")"
              rounddown="$(date -u -d@"$(($timestamp/3600*3600))" +%Y-%m-%dT%H:%M:%SZ)"
              roundup="$(date -u -d@"$((($timestamp/3600 +1)*3600))" +%Y-%m-%dT%H:%M:%SZ)"
              # Number of licensed users, divided by 720 (24 hours x 30 days in month)
              # By reporting this fraction every hour, each month the cumulative total is the monthly bill.
              # using "bc" for calculation because shell only handles integers
              userfraction="$( echo "scale=5;{{ .Values.numberOfLicenses }}/720" | bc)"
              echo "Users divided by hours in month: ${userfraction}" >&2
              postbody="{\"name\":\"{{ .Values.pricingPlan }}\", \"startTime\": \"$rounddown\",\"endTime\": \"$roundup\",\"value\": { \"DoubleValue\": $userfraction } }"
              echo "${postbody}" >&2
              curl -X POST -d "${postbody}" "http://localhost:4567/report"
              # repeat this every hour
              sleep 3600
            done
      volumes:
      - name: ubbagent-config
        configMap:
          name: ubbagent-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
